# Generated by Django 5.0.6 on 2024-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_despesamensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesamensal',
            name='valor_total',
            field=models.FloatField(),
        ),
    ]
